/**
 * Publishing sites booking API
 * This is a sample API for handling bookings on publishing sites.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: apiteam@swagger.io
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
 import { Booking } from './booking';

 export interface Timeslot { 
     start?: Date;
     end?: Date;
     bookingList?: Array<Booking>;
     /**
      * Order Status
      */
     status?: Timeslot.StatusEnum;
 }
 export namespace Timeslot {
     export type StatusEnum = 'free' | 'complete' | 'uncomplete';
     export const StatusEnum = {
         Free: 'free' as StatusEnum,
         Complete: 'complete' as StatusEnum,
         Uncomplete: 'uncomplete' as StatusEnum
     };
 }